version: 2
jobs:
  build:
    working_directory: ~/DockYard/ember-composable-helpers
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: node-modules-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install packages
          command: yarn
      - save_cache:
          key: node-modules-cache-{{ checksum "yarn.lock" }}
          paths:
           - node_modules
      - run:
          name: Run tests
          command: yarn test
            esac
      - store_test_results:
          path: test-results
